// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeStore.Data;

#nullable disable

namespace RecipeStore.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20220826191339_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeStore.Model.Ingredients", b =>
                {
                    b.Property<string>("IngredientCode")
                        .HasColumnType("varchar(900)");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("varchar(900)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("IngredientCode", "RecipeCode");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeStore.Model.Recipe", b =>
                {
                    b.Property<string>("RecipeCode")
                        .HasColumnType("varchar(900)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("PreparationTime")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("RecipeCode");

                    b.ToTable("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
